# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TorrentDownloader.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(793, 645)
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.searchBar = QtGui.QLineEdit(self.centralwidget)
        self.searchBar.setGeometry(QtCore.QRect(22, 19, 621, 31))
        self.searchBar.setFrame(True)
        self.searchBar.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchBar.setDragEnabled(True)
        self.searchBar.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.searchBar.setObjectName(_fromUtf8("searchBar"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 430, 771, 91))
        self.groupBox.setStyleSheet(_fromUtf8(""))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.progressBar = QtGui.QProgressBar(self.groupBox)
        self.progressBar.setGeometry(QtCore.QRect(10, 20, 751, 23))
        self.progressBar.setMouseTracking(False)
        self.progressBar.setFocusPolicy(QtCore.Qt.NoFocus)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.status = QtGui.QLineEdit(self.groupBox)
        self.status.setGeometry(QtCore.QRect(210, 60, 341, 20))
        self.status.setFocusPolicy(QtCore.Qt.NoFocus)
        self.status.setText(_fromUtf8(""))
        self.status.setFrame(False)
        self.status.setAlignment(QtCore.Qt.AlignCenter)
        self.status.setReadOnly(True)
        self.status.setObjectName(_fromUtf8("status"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 20, 121, 31))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tableWidget = QtGui.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 70, 751, 351))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.verticalHeader().setSortIndicatorShown(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOptions = QtGui.QMenu(self.menubar)
        self.menuOptions.setObjectName(_fromUtf8("menuOptions"))
        self.menuTasks = QtGui.QMenu(self.menubar)
        self.menuTasks.setObjectName(_fromUtf8("menuTasks"))
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(50, 50))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionTutorials = QtGui.QAction(MainWindow)
        self.actionTutorials.setObjectName(_fromUtf8("actionTutorials"))
        self.actionDownload = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/download2.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.actionDownload.setIcon(icon)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(10)
        self.actionDownload.setFont(font)
        self.actionDownload.setObjectName(_fromUtf8("actionDownload"))
        self.actionResume = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/resume.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionResume.setIcon(icon1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionResume.setFont(font)
        self.actionResume.setObjectName(_fromUtf8("actionResume"))
        self.actionPause = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/pause.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPause.setIcon(icon2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionPause.setFont(font)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionStop.setFont(font)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionDonate = QtGui.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionDonate.setFont(font)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionLocation = QtGui.QAction(MainWindow)
        self.actionLocation.setObjectName(_fromUtf8("actionLocation"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionContact = QtGui.QAction(MainWindow)
        self.actionContact.setObjectName(_fromUtf8("actionContact"))
        self.menuOptions.addAction(self.actionTutorials)
        self.menuOptions.addSeparator()
        self.menuOptions.addAction(self.actionContact)
        self.menuOptions.addAction(self.actionAbout)
        self.menuOptions.addAction(self.actionDonate)
        self.menuTasks.addAction(self.actionDownload)
        self.menuTasks.addSeparator()
        self.menuTasks.addAction(self.actionResume)
        self.menuTasks.addAction(self.actionPause)
        self.menuTasks.addAction(self.actionStop)
        self.menuTasks.addAction(self.actionLocation)
        self.menuTasks.addSeparator()
        self.menuTasks.addAction(self.actionExit)
        self.menubar.addAction(self.menuTasks.menuAction())
        self.menubar.addAction(self.menuOptions.menuAction())
        self.toolBar.addAction(self.actionDownload)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionResume)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPause)
        self.toolBar.addSeparator()
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.searchBar.setText(_translate("MainWindow", "", None))
        self.searchBar.setPlaceholderText(_translate("MainWindow", "Search softwares on Torrent", None))
        self.status.setPlaceholderText(_translate("MainWindow", "Nothing to Download", None))
        self.pushButton.setText(_translate("MainWindow", "Search", None))
        self.menuOptions.setTitle(_translate("MainWindow", "Help", None))
        self.menuTasks.setTitle(_translate("MainWindow", "Tasks", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionTutorials.setText(_translate("MainWindow", "Tutorials", None))
        self.actionDownload.setText(_translate("MainWindow", "Download", None))
        self.actionDownload.setStatusTip(_translate("MainWindow", "Download", None))
        self.actionResume.setText(_translate("MainWindow", "Resume", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionDonate.setText(_translate("MainWindow", "Donate", None))
        self.actionLocation.setText(_translate("MainWindow", "Default Save Location", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionContact.setText(_translate("MainWindow", "Contact", None))

import icons_rc
